### ISSUE TITLE
Diff not computed correctly if the text lines end with \r\n

### ISSUE THREAD

**Issue by AlexandraColdea** [ace-diff/ace-diff#1]
If you populate the editors with content that has both the CR and LF characters at the end of each line (for example, importing a file from a Linux environment), the diff is not computed correctly. 

I suspect that it's the way the line lengths are computed in this method: getLineLengths.

Here is an example of how it behaves in this case:
![screen shot 2015-04-07 at 09 33 22](https://cloud.githubusercontent.com/assets/6747174/7019595/829ba68c-dd09-11e4-8a0c-36b93b7ea30b.png)

**Comment by benkeen** [comment]
Thanks, @AlexandraColdea! I'll try to look at that this weekend.

**Comment by benkeen** [comment]
Sorry - I didn't manage to look at this yet. I'll try this week.

**Comment by cd8** [comment]
You can use .replace(/\n/mg, "") to make this work as it removes the additional \n
