### ISSUE TITLE
Few Requirement in ace diff page .

### ISSUE THREAD

**Issue by vinothwindows47** [ace-diff/ace-diff#11]
Random Font size not working in ace diff page:
Ace diff font size is too small . If I change font-size in ace diff tool, diff connector is not working properly .
For Example : 

 Default Font size in ace diff : 

![default-font-size](https://cloud.githubusercontent.com/assets/3929019/11455579/e6334adc-968c-11e5-925a-27b48910da52.png)

Custom Font Size in ace diff is not properly connector working:

![custom-fontsize](https://cloud.githubusercontent.com/assets/3929019/11455583/f557f0f8-968c-11e5-80fe-9254eb180992.png)

Set Use Word Wrap is not working : 

![wordwrap-issue](https://cloud.githubusercontent.com/assets/3929019/11455617/cd21cfe0-968d-11e5-9c17-448286042f91.png)

@nicolashenry  @benkeen  Diff compare is not a problem.But connectors only problem . Please my humble request fix it as soon as possible . Because we are using ace diff tool . Previously We have been using mergely tool .http://www.mergely.com/editor . It also so cool for showing diff and merge page .

**Comment by vinothwindows47** [comment]
@benkeen @nicolashenry Please response my problems . whether it is possible to fix it or not .

**Comment by benkeen** [comment]
Hi @vinothwindows47, sorry for the wait! Hmm... you may be right. I was under the impression that you could just style the connectors with CSS to change their line heights, but apparently my memory was incorrect. 

I'll do a little investigation and get back to you shortly.

**Comment by benkeen** [comment]
Heya, again sorry for the wait. 

1. So *word-wrap* is a bug. I'll create a separate issue for that one - well spotted.
2. How do you set the custom font-sizes? Ace works by keeping track of the calculated line-heights, then making them accessible via `ace.renderer.lineHeight` - which ace-diff uses to determine the height of the connector lines. So in my case it seems to be working fine. see screenshot of font-size:18px

<img width="1441" alt="screen shot 2015-12-04 at 4 58 12 pm" src="https://cloud.githubusercontent.com/assets/512116/11614296/24adf7ec-9bf3-11e5-8144-3a1bb020236f.png">

This changes the font like so: `body .ace-editor { font-size: 18px }`

could you post your CSS that's changing the font-size but causes the bug?

**Comment by benkeen** [comment]
Hey again - sorry for all the posts. Regarding the word-wrap, did you enable that by editing the ace-diff JS code? Correct me if I'm wrong, but currently ace-diff doesn't support that feature, correct?

**Comment by Spope** [comment]
I don't know for @vinothwindows47 but at first I have used the Ace api for font size : `this.differ.editors.left.ace.setFontSize(14); this.differ.editors.right.ace.setFontSize(14);` 
and this create the same connectors alignment problem.
Anyway, setting font size by css does actually works correctly.

**Comment by vinothwindows47** [comment]
Ok.Thank you @Spope .I will try it .

**Comment by vinothwindows47** [comment]
Hi @Spope .I have set in css like this body .ace-editor { font-size: 18px } . (or)
I have set in ace API like this this.differ.editors.left.ace.setFontSize(14); 
These two cases are not working .I hope definitely if you change font-size either css change or ace api, the connector problem will occur .

**Comment by vinothwindows47** [comment]
Thanks @benkeen @Spope .Font size working as usual . It is my fault . Because I have set fontsize after 

this.lineHeight = this.editors.left.ace.renderer.lineHeight;

So that it is not working .But it is working when i set like this ,

this.editors.left.ace.setFontSize("15px");
this.editors.right.ace.setFontSize("15px");

 this.lineHeight = this.editors.left.ace.renderer.lineHeight;
