### ISSUE TITLE
Question/ Feature request

### ISSUE THREAD

**Issue by idantr** [ace-diff/ace-diff#16]
Hi,
Is there something that can be done the will compare text without leading and trailing spaces of all kind ( tab, cr cf etc.), some way/attribute to disregard spaces in the comparison.
ex.

file content 1:
1:      test1
file content 2:
1:test1

currently i will get row #1 marked as containing a change but the texts are the same i would like to be able to decide which result i want
Cheers
idan.

**Comment by JackuB** [comment]
Hey, you could normalise the content before comparing them. Don't think this scenario would be really useful, if texts are different. And if you are worried about for examples differences between spaces and tabs, you should normalise the files anyway.
