### ISSUE TITLE
ace-diff redo undo not working while merge from one side to other side

### ISSUE THREAD

**Issue by vinothwindows47** [ace-diff/ace-diff#18]
Using ace-diff tool, we can't do redo and undo while merging from one side to other side .

But CodeMirror doing redo and undo option,

CodeMirror Mergetool Url :  http://codemirror.net/demo/merge.html#

**Comment by vinothwindows47** [comment]
@benkeen @BlaneCordes @MustafaHaddara the above mentioned issue fixed ?

**Comment by hdytsgt** [comment]
@vinothwindows47 Take a look at this : https://github.com/benkeen/ace-diff/blob/master/dist/ace-diff.js#L324 it's because setValue() which reset $undostack - to avoid this you can change that line into following :

```
targetEditor.ace.getSession().doc.setValue(startContent + contentToInsert + endContent);
```
