### ISSUE TITLE
project description wrong link

### ISSUE THREAD

**Issue by cancerberoSgx** [ace-diff/ace-diff#23]
The link in the project description say http://benkeen.github.io/ace-diff/ but it should be http://benkeen.github.io/ace-diff/

Also links in README

Probably in other places too

Nice project BTW

**Comment by JackuB** [comment]
Forgot GH is only handling redirects on repo URL, not GitHub pages URL.

@benkeen could you please setup the redirect? And change the URL in the project description? I don't have enough rights…

**Comment by benkeen** [comment]
Sure - np! Just travelling at the moment, but will be back in a couple of days. I'll fix this up then, sorry for the wait.

**Comment by benkeen** [comment]
I've patched up the link in the main projects description and in the README, but couldn't find a spot to add a redirect from the old (non-existent) location to the new - at least, not without creating another repo on my own account & adding it there. But I think the fixed links will suffice.
