### ISSUE TITLE
css

### ISSUE THREAD

**Issue by cancerberoSgx** [ace-diff/ace-diff#24]
unless one uses exactly your css with flexbox is virtually impossible to understand what to do - you should provide an other example, or minimal requirements like putting colors, alignment, etc. An example using a table or just divs could help people to understand what to do - also a minimal css for that - a very minimal css would be nice - one that dont use absolutes , relatives or flexbox - just inline/block. Also the gutter svg and others don't a have default colors and this makes really hard to understand how to make it work

**Comment by JackuB** [comment]
Yup, agreed. Currently refactoring some parts of this project to make it easier to embed/interop with other elements on the page.
