### ISSUE TITLE
Bower package out of date

### ISSUE THREAD

**Issue by teirich** [ace-diff/ace-diff#30]
Hey @gad2103, I see you added your fork to bower but it's not in sync.  I spent a long time figuring out why my ace-diff dist wasn't working with brace, and it's because you haven't updated pulled your fork since 2015.  If you're not going to keep that fork up to date, you should namespace the project so other people aren't pulling in your personal changes. Can we get bower ace-diff to point to the main repo?  

https://github.com/gad2103/ace-diff

**Comment by JackuB** [comment]
Bower is being phased out, closing this
