### ISSUE TITLE
Semi-colon causes the diff to insert incorrectly

### ISSUE THREAD

**Issue by lofty-ometis** [ace-diff/ace-diff#31]
In the first attached image the semi-colon on the right seems to be causing an issue. 
The semi-colon only exists in the right pane, where-as in the left pane it exists further down after some further parameters have been added. The code therefore wants to insert the additional code from the left-pane above the code on the right, but it should include and replace the bottom line on the right.
![chrome_2018-03-19_16-55-49](https://user-images.githubusercontent.com/28395453/37610043-8880c6e8-2b96-11e8-9eae-46573597dc3b.png)

This second attachment shows what I'd expect to happen. I've simply replaced the semi-colon with another random charcter '>' to prove my point:
![chrome_2018-03-19_16-59-02](https://user-images.githubusercontent.com/28395453/37610264-1203fb1a-2b97-11e8-86a0-514e4f8c7c8e.png)

Please can you help me with escaping semi-colons or suggest a fix?

**Comment by JackuB** [comment]
@lofty-ometis could you please paste here the strings in editors so I could debug them? At least the offending part.

**Comment by lofty-ometis** [comment]
Hi,
I realised that it may not be an issue with your package but that it doesn't support the language (Qlik) I was hoping to use it for.

Do you intend to make it easily adaptable for other languages?

Thanks.

**Comment by JackuB** [comment]
@lofty-ometis ace-diff is language independent - you can just specify the Mode with the ace-diff API https://github.com/ace-diff/ace-diff#diffing-settings
