### ISSUE TITLE
Diffing error

### ISSUE THREAD

**Issue by intrepidOlivia** [ace-diff/ace-diff#32]
Hello, I think I have found an error in the diffing display in the demos provided. I used the JSON objects [pasted here](https://pastebin.com/Qv0Gsevj) on [Demo 1](http://ace-diff.github.io/ace-diff/demos/demo1/) to check the diffing display, and it seems that the display on line 27 on the left side and 24-27 on the right side are incorrect. 

I believe the correct display would be to highlight line 25 on the left side, and lines 23 and 24 on the right side.

![image](https://user-images.githubusercontent.com/3474569/38339975-d16acfde-3825-11e8-91c4-9068b288a964.png)

**Comment by JackuB** [comment]
Hmm, interesting. In relation to #28 I will have to take deeper look at the diffing logic

**Comment by kaffee-kocher** [comment]
+1

**Comment by JackuB** [comment]
Took some time, but PR #69 solves this it seems

<img width="1344" alt="Screenshot 2020-05-24 at 21 39 22" src="https://user-images.githubusercontent.com/1788727/82763308-0be8fe80-9e07-11ea-824b-39da26957a25.png">
