### ISSUE TITLE
I think there might be something wrong with the logic

### ISSUE THREAD

**Issue by zrx8269** [ace-diff/ace-diff#40]
I am using ace-diff v2.1.2.
In my source code, there are some errors

1. In the right editor, the blue line should be drawn between line 35 and 36. For the source code before version 1.0.0, this works properly.
![image](https://user-images.githubusercontent.com/13849260/40048350-9cb9245c-5864-11e8-9529-746f37f0f7c4.png)

2. In the right editor, only line 150 should be marked. For the source code before version 1.0.0, this also works properly.
![image](https://user-images.githubusercontent.com/13849260/40049733-1a339de2-5868-11e8-868c-f97d8f5d18d3.png)

3. One new line at the end is not marked.
![image](https://user-images.githubusercontent.com/13849260/40049102-5a0daff4-5866-11e8-9043-6c57566904f3.png)

**Comment by JackuB** [comment]
It seems that PR #69 fixes the issue
See this comment https://github.com/ace-diff/ace-diff/issues/41#issuecomment-633283839
