### ISSUE TITLE
something wrong with the \n

### ISSUE THREAD

**Issue by zrx8269** [ace-diff/ace-diff#41]
Hi,
In my project, there are some problems to show the difference.
![bug](https://user-images.githubusercontent.com/13849260/40635962-4fc901c8-632f-11e8-84f7-b0c095e98681.png)

In the left editor, I think the line under line 1 should be moved to line 2.
In the right editor,  the line under line 13 should be moved to line 14.

You can try the attached code to reproduce the bug.
[errorCode.txt](https://github.com/ace-diff/ace-diff/files/2046630/errorCode.txt)

**Comment by JackuB** [comment]
It took some time, but #69 fixes this issue.

<img width="1344" alt="Screenshot 2020-05-24 at 21 32 47" src="https://user-images.githubusercontent.com/1788727/82763204-38504b00-9e06-11ea-90b1-94a08a35a8c0.png">

Behaves as expected, without introducing weird changes when trying to apply L->R or R->L
