### ISSUE TITLE
display none breaks gutter

### ISSUE THREAD

**Issue by gad2103** [ace-diff/ace-diff#5]
if the editors are display:none and then set to be displayed the SVG and gutter arrows break because of width and height calculations see https://github.com/benkeen/ace-diff/blob/master/dist/ace-diff.js#L87
and
https://github.com/benkeen/ace-diff/blob/master/dist/ace-diff.js#L684
https://github.com/benkeen/ace-diff/blob/master/dist/ace-diff.js#L685

i have a fork and i've put in some defaults that basically match the default vaules for ace editor. 

i can send a PR but i'm not sure if hard coding the values is really the best alternative. might be better to check the display property and if it is none, then clone the editors and inject them into the dom off the page and then set the dimensions and then destroy the cloned nodes.

**Comment by JackuB** [comment]
Reworked the CSS, hopefully this is now resolved.
Feel free to reopen.
