### ISSUE TITLE
How to take uncompressed ace-diff latest version ?

### ISSUE THREAD

**Issue by vinothwindows47** [ace-diff/ace-diff#51]

**Comment by JackuB** [comment]
You mean this one? https://github.com/ace-diff/ace-diff/blob/master/src/index.js

Unminified built version is not part of the release. You have any use case for that?

**Comment by vinothwindows47** [comment]
I am using ace-diff - v1.0.0 - I have changed a lot in that ace-diff version . But currently ace diff - v2.2.0 totally different from v1.0.0. I have some bug in that (1.0.0) ace diff due to ace version migration changes . I want fix it to migrate latest version . But I can't migrate latest version .

**Comment by JackuB** [comment]
I’m not following. 

Anyway, you could always build whatever you need from ES6 source.
If there is a bug, want to share it so we can fix current version? Or what did you change in your v1 copy?

**Comment by vinothwindows47** [comment]
Hi @JackuB ,

     I want some features in ace-diff new version ,

1. **Wrap Lines** options in diff mode .
2. **Synchronize scroll** option
3. **Exact Line Diff** 
![ace_diff_exact_line_diff](https://user-images.githubusercontent.com/3929019/43988616-2d36febe-9d57-11e8-83e0-2bc9c68fbd03.png)
4. **Navigate Next and Prev Diff** Option
![navigate_next_diff_option](https://user-images.githubusercontent.com/3929019/43988633-bc7931d2-9d57-11e8-9766-d1a51d7a2a94.png)
5. **Ignoring White Space** option
6. **Inline Diff View** - Ace Diff

**Comment by vinothwindows47** [comment]
@JackuB - Any idea about this ?

**Comment by JackuB** [comment]
Any chance you could open pull requests with the things you developed/want?

**Comment by vinothwindows47** [comment]
Initially, I will do migrate it with the latest one and verify the changed code and send pull request .
