### ISSUE TITLE
aceEditor.setValue vs aceEditor.replace

### ISSUE THREAD

**Issue by shds86** [ace-diff/ace-diff#52]
Why don't you use aceEditor.replace for inserting text but use setValue? As i know setValue clears undoredo manager after that impossible to use Ctrl+Z/Y.

**Comment by JackuB** [comment]
Hey, good point - also, just found out it's also mentioned here https://github.com/ace-diff/ace-diff/issues/18 , haven't noticed that comment before. Will create a patch
