### ISSUE TITLE
Support ace-builds (instead of/in addition to) brace

### ISSUE THREAD

**Issue by fr0** [ace-diff/ace-diff#67]
```
ERROR in ./node_modules/ace-diff/src/index.js
Module not found: Error: Can't resolve 'brace' in '.../node_modules/ace-diff/src'
```

[brace](https://github.com/thlorenz/brace) is updated infrequently (if at all, it really hasn't been changed in years).

[ace-builds](https://github.com/ajaxorg/ace-builds) is maintained by the team that builds ace, and supports use via webpack/browserify. There's really no reason to specifically require `brace` anymore.

**Comment by JackuB** [comment]
Glad to see official ace packages. I’ve played with refactoring ace-diff to use ace npm today and it’s doable, but can’t see a way to not make it a breaking change.

**Comment by crfrolik** [comment]
Thanks for the update. I've been using it with `ace-builds` for a while now via this (very ugly) `postinstall` script:

```
perl -i -pe's/brace/ace-builds/g' node_modules/ace-diff/src/index.js
```

It's gross, but I decided it's preferable to forking the package.

**Comment by JackuB** [comment]
Closing, as it is now part of the latest v3 🎉
