### ISSUE TITLE
Range module acequire fail

### ISSUE THREAD

**Issue by luocongqiu** [ace-diff/ace-diff#71]
**version**
ace-diff: 3.0.1
brace: 0.11.1

**conosle**
Could not require Range module for Ace. Depends on your bundling strategy, but it usually comes with Ace itself. See https://ace.c9.io/api/range.html, open an issue on GitHub ace-diff/ace-diff

**Comment by JackuB** [comment]
Hey, got more details on how you run ace-diff?

**Comment by luocongqiu** [comment]
Hey, I use ace-diff in a angular project

**component**

`import { AfterViewInit, Component, ElementRef, OnDestroy, OnInit } from '@angular/core';

import AceDiff from 'ace-diff/src';
import * as ace from 'brace';

@Component({
    selector: 'ai-select-c',
    templateUrl: 'test.component.html',
    styleUrls: ['test.scss']
})
export class TestComponent implements OnInit, AfterViewInit, OnDestroy {


    constructor(private elementRef: ElementRef<HTMLElement>) {
    }

    ngOnInit(): void {
    }


    ngAfterViewInit(): void {

        const differ = new AceDiff({
            ace, // using Brace
            element: this.elementRef.nativeElement,
            left: {
                content: 'your first file content here'
            },
            right: {
                content: 'your second file content here'
            }
        });
        console.info(differ);
    }

    ngOnDestroy(): void {
    }

}
`
**console**

Error: Could not require Range module for Ace. Depends on your bundling strategy, but it usually comes with Ace itself. See https://ace.c9.io/api/range.html, open an issue on GitHub ace-diff/ace-diff
    at new L (ace-diff.min.js:30)
