### ISSUE TITLE
Warning from webpack when using ace-diff 3

### ISSUE THREAD

**Issue by crfrolik** [ace-diff/ace-diff#72]
```
WARNING in ./node_modules/ace-diff/dist/ace-diff.min.js 1:292-296
Critical dependency: the request of a dependency is an expression
```

I suspect ace-diff is doing some dynamic `require` that webpack doesn't like. FYI I think webpack is fine with having `require` statements that are conditionally executed but has trouble with dynamic expressions in the `require` call itself. Could the code be refactored somehow to improve this?

Thanks for all the hard work on this library!

**Comment by crfrolik** [comment]
Oddly this warning doesn't happen if I change ace-diff's entry point from `dist/ace-diff.min.js` to `src/index.js`.

**Comment by JackuB** [comment]
Hey, I couldn't replicate this with a minimal webpack setup. You can avoid modifying the package.json and try importing/requiring the specific source that you want e.g.

```diff
- import * as AceDiff from 'ace-diff'
+ import * as AceDiff from 'ace-diff/src/'
```

I think I'll remove the browser field, as `module` should be enough, consider there isn't a browser-specific distribution.
